/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/UnityDraco.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.005']} position={[-0.72, 0.99, -0.84]} />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[-0.71, 0.98, -0.83]}
        scale={[0.99, 0.9, 0.91]}
      />
    </group>
  )
}

useGLTF.preload('/UnityDraco.glb')
