/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { SimpleGeometry } from "./SimpleBox";
import {useBox, Debug, useTrimesh, useCompoundBody, useConvexPolyhedron} from "@react-three/cannon"
import { Canvas, useFrame, useThree, } from "@react-three/fiber";

import { meshBounds, Center } from "@react-three/drei";
import { PlainImages } from "../settings/Boxes";
import model from './frog.glb'


export const Frog = forwardRef((props, ref) =>{
  const { nodes, materials } = useGLTF(model);
  return (
    <>
    <group ref={ref} {...props} dispose={null}>
    <mesh geometry={nodes.frog.geometry} material={materials.frog} rotation={[Math.PI/2, 0, 0]}position={[0.08, 0, -0.2]} scale={[3,1,3]}/>
  </group>

    </>
  );
})

useGLTF.preload(model)
export default Frog