/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState, forwardRef  } from 'react'
import { useGLTF } from '@react-three/drei'

import { Canvas, useFrame, useThree, } from "@react-three/fiber";

import { SimpleGeometry } from "./SimpleBox";
import {useBox, Debug, useTrimesh, useCompoundBody, useConvexPolyhedron} from "@react-three/cannon"

import { meshBounds, Center } from "@react-three/drei";
import { GIcon } from "../settings/Boxes";

import model from './gitIcon.glb'


export const GitIcon = forwardRef((props, ref) =>{
  const { nodes, materials } = useGLTF(model);
  return (
    <>
    <group ref={ref}  {...props} dispose={null}>
      <mesh raycast={meshBounds} geometry={nodes.Curve.geometry} material={materials['SVGMat.001']}rotation={[0, Math.PI, 0]} scale={[3275.04, 766.11, 3275.04]} />
    </group>

    </>
  );
})
useGLTF.preload(model)
export default GitIcon