/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useEffect, useState, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import model from "./linkicon.glb"
import { Canvas, useFrame, useThree, } from "@react-three/fiber";

import { SimpleGeometry } from "./SimpleBox";
import {useBox, Debug, useTrimesh, useCompoundBody, useConvexPolyhedron} from "@react-three/cannon"

import { meshBounds, Center } from "@react-three/drei";
import { LIcon } from "../settings/Boxes";



export const LnIcon = forwardRef((props, ref) =>{
  const { nodes, materials } = useGLTF(model);
  return (
    <>
    <group {...props}  dispose={null}>
    <mesh   raycast={meshBounds} geometry={nodes.Curve001.geometry} material={materials['SVGMat.002']} scale={2964.24} />
  </group>

    </>
  );
})
useGLTF.preload(model)
export default LnIcon