/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import {SimpleGeometry} from './SimpleBox';
import model from "./placard.glb";
import {PlacardBoxes} from "../settings/Boxes"
import { useBox, Debug, useCompoundBody } from "@react-three/cannon";


export const Placard = forwardRef((props, ref) =>{
  const { nodes, materials } = useGLTF(model);
  return (
    <>
    <group ref={ref} {...props} dispose={null}>
      <group  scale={[0.95, 0.09, 5.98]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.003']} />
      </group>
      <mesh
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[.2, 0.1, 4.11]}
        rotation={[Math.PI / 2, Math.PI / 2, -Math.PI / 2]}
      />
    </group>

    </>
  );
})
useGLTF.preload(model)
export default Placard