/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { SimpleGeometry } from "./SimpleBox";
import {useBox, Debug, useTrimesh, useCompoundBody, useConvexPolyhedron} from "@react-three/cannon"
import { Canvas, useFrame, useThree, } from "@react-three/fiber";
import { PlainImages } from "../settings/Boxes";

import { meshBounds, Center } from "@react-three/drei";
import model from './trowel.glb'



export const Trowel = forwardRef((props, ref) =>{
  const { nodes, materials } = useGLTF(model);
  return (
    <>
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.Untitled.geometry} material={materials.Untitled} rotation={[Math.PI/2, 0, 0]}scale={[3,1,3]}position={[0.08, 0, -0.2]} />
    </group>

    </>
  );
})
useGLTF.preload(model)
export default Trowel