/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import * as THREE from "three";
import model from "./unityLogo.gltf";
import styled from "styled-components";
import { Canvas, MeshProps, useFrame, useThree } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { MathUtils } from "three";

export default function UnityLogo(props) {
  const { nodes, materials } = useGLTF(model);
  let decrease = false;

  const mesh = useRef();

  useFrame((state, delta) => {
    let progress = 0;

    if (mesh.current.position.y >= 0.2) {
      decrease = true;
      progress = 0;
    } else if (mesh.current.position.y <= -0.2) {
      decrease = false;
      progress = 0;
    }
    if (decrease) {
      progress += 0.03;
      mesh.current.position.y = MathUtils.lerp(
        mesh.current.position.y,
        -1,
        progress
      );
    } else {
      progress += 0.03;
      mesh.current.position.y = MathUtils.lerp(
        mesh.current.position.y,
        1,
        progress
      );
    }
  });

  return (
    <group ref={mesh} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[0, 0, 0.3]}
        rotation={[0.5, -0.8, 0]}
        scale={2.5}
      />
    </group>
  );
}

useGLTF.preload(model);
